name: scribe_lib
description: scribe shared library
version: 0.0.1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  quiver: ^3.1.0
  basics: ^0.9.0
  tuple: ^2.0.0
  freezed_annotation: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1

flutter:
