name: scribe_lib
description: scribe shared library
version: 0.0.1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  quiver: ^3.2.1
  basics: ^0.10.0
  tuple: ^2.0.1
  freezed_annotation: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
