name: scribe
description: Character tracing

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_tts: ^3.6.3
  tuple: ^2.0.1
  basics: ^0.10.0
  quiver: ^3.2.1
  google_fonts: ^4.0.3
  freezed_annotation: ^2.2.0
  provider: ^6.0.5
  scribe_lib:
    path: ../scribe_lib

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.3.2
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
